-- PREGAO — itens de research coletados das casas (Genial Analisa etc.)
-- Rode isso uma vez em: Supabase > SQL Editor > New query

create table if not exists research_itens (
  link          text primary key,          -- URL do relatorio original, chave unica (upsert)
  casa          text not null,              -- ex: 'Genial Analisa'
  titulo        text not null,
  data          text,                       -- data do relatorio, 'YYYY-MM-DD' (como vem da fonte)
  autor         text,
  tipo          text not null,              -- ACOES / ESTRATEGIA / MACRO / NEWSLETTER
  tickers       text[] not null default '{}',
  resumo        text,                       -- resumo por IA, com palavras proprias - NUNCA o texto completo
  modelo_resumo text,                       -- ex: 'openai/gpt-oss-20b' (qual LLM gerou o resumo)
  coletado_em   timestamptz not null default now()
);

create index if not exists idx_research_itens_casa on research_itens (casa);
create index if not exists idx_research_itens_data on research_itens (data desc);

-- RLS ativado e SEM policies: o backend Python usa a secret key, que
-- sempre ignora RLS. Nenhuma outra chave (ex: anon) consegue ler ou
-- escrever nessa tabela. Mesmo padrao de sql/schema.sql (user_prefs).
alter table research_itens enable row level security;

-- ============================================================
-- Research Intelligence (2026-10-01) — rode isso uma vez também,
-- idempotente (if not exists em tudo, seguro re-rodar).
-- ============================================================

-- preco_alvo/recomendacao: extraidos do PROPRIO documento (so' quando
-- explicitos no texto - ver data/research/resumir.py:_extrair_dados_estruturados)
-- - NUNCA estimados pelo modelo. Nullable de proposito: a maioria dos
-- documentos (macro, newsletter, estrategia) nao tem preco-alvo nenhum.
alter table research_itens add column if not exists preco_alvo numeric;
alter table research_itens add column if not exists recomendacao text;

-- research_recomendacoes_historico: snapshot de CADA MUDANCA real de
-- preco-alvo/recomendacao por casa+ticker (fonte: obter_recomendacoes()
-- da Genial hoje - unica fonte com dado estruturado pronto; outras casas
-- podem alimentar essa mesma tabela no futuro). NAO e' perecivel como
-- research_itens (5 dias) - e' justamente o historico que
-- research_itens, por design, nao guarda. So' grava uma linha NOVA
-- quando recomendacao/preco_alvo realmente mudam desde o ultimo
-- snapshot (ver data/research/historico.py) - poucas linhas por
-- ticker/ano, cresce devagar.
create table if not exists research_recomendacoes_historico (
  id            bigint generated by default as identity primary key,
  casa          text not null,
  ticker        text not null,
  recomendacao  text,
  preco_alvo    numeric,
  potencial_pct numeric,
  capturado_em  timestamptz not null default now()
);

create index if not exists idx_research_hist_casa_ticker
  on research_recomendacoes_historico (casa, ticker, capturado_em desc);

alter table research_recomendacoes_historico enable row level security;

-- ============================================================
-- FASE 3 — feed editorial NEWS+RESEARCH (2026-10-08) — idempotente.
-- ============================================================

-- publicado_em: timestamp COMPLETO (data+hora) de publicacao, hoje so'
-- preenchido pelas lives da Genial (Morning Call/Resumo da Manha/
-- Fechamento etc - ver data/research/genial_lives.py) - usado so' pra
-- posicionar esses itens cronologicamente (hora certa) dentro do feed
-- unificado do NEWS (ver ui/news_tab.py). 'data' (so' o dia) continua
-- sendo a coluna que o resto do projeto usa - nullable de proposito,
-- a maioria dos itens (research normal) nao tem isso.
alter table research_itens add column if not exists publicado_em timestamptz;
